services:
  postgres:
    image: postgres:18
    container_name: payment-app-postgres
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: payment_user
      POSTGRES_PASSWORD: payment_pass
      PGDATA: /var/lib/postgresql/18/main
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/18/main
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
