server:
  port: 8082
  servlet:
    context-path: /product

spring:
  application:
    name: product
  thymeleaf:
    check-template-location: false
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_db
    username: payment_user
    password: payment_pass
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 2
      max-lifetime: 1800000
      validation-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    locations: classpath:db/migration
