server:
  servlet:
    context-path: /payment

spring:
  application:
    name: payment
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_db
    username: payment_user
    password: payment_pass
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 2
      max-lifetime: 1800000
      validation-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    locations: classpath:db/migration

integrations:
  clients:
    payments-executor-client:
      url: http://localhost:8089/executor
      connect-timeout: 5s
      read-timeout: 10s
      execute-url: /payments/execute
      execute-url-500: /payments/execute/500
